travis:
  secure:
    BINSTAR_TOKEN: OVDbILATL9QSuOrAAviSNdNAWJ6MvASKjlhGp7mCyXg5NTszRmFy2hx44OIKJJd/ULKy2U/1vun2NmxR1gQx8SnuCns3p+Fs5cskOENZ39SoaLWSjPH2inUEIMlMkDdUNiexkhlX5ItFM1OtY1lXWDyMdh6CLF/zfHda/2PEb0HlppH8/d4/pi57nKpThiXbkMOx5YqYj0/wuAKCpROhFAPGNHvsa87MUH26Oe0rcVtE8tegNhToZyfA3SRzXadBRkzOnxr2XsV5AKbzBt8EG0ytjmBik2fOQWHISHtDxyQvJA9D5XOe0k8c6GNEFc+mg5A0xa2aImknwPillltSJoXVjJlCE392Cj2sad0zx2qh6yunvEHEhq5rx3D+T+qy8uXwONnqRbn2SzE1mLBI6GeL0S0yDZ/DcfJZN+wopyQWUUGSIM1Eh93XApXJmhHL/P9+yZe64m1f9tafjd2hjwu8OMteB0Ng7abRAQl9kI/1oWpTDvc4Vmi68TuJhZf2UIjWxBZ1YCXFhI0kaea6u1mYV3USCSNVydragR5G14i2W0e/lN1Qvfoir9rZ0qkHrKL8kqWMEqpeMOAKXmPND4SrEEQRFiK6AEI5uJ/m7wCut3XExdm7Ex2In2CYq5CKPxPFeCRQ2gxYZoSQLeT7vDg+F9+ZdaPD84PlYEqdLxg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
