travis:
  secure:
    BINSTAR_TOKEN: DuFxw5k+GsXL8Mna6L33tJBl/F3B8Sb9bFgoqvJ4TaF4WgY0054LzBLStkx3FCr2O6b7FqN7QCg7IHlOnfAFiIppRLnM7r/puYPaMcFpKk+nGTU03LsvAt7BqIrTgE7MoIMmoJDpilwslUCVASP21GM4+U9E5NyomBMKdplTTNZTXgmDMgzTu74SXahPabr4b9RFqH6mt2nAvVROmYUwJUrWelsDmLvY99HG4cpxHhXiBT+HHP6BNzF+AOWUDVanDqnl3hGA36luVyhMaA2qmZupERuLsGFrCl0SZWX6VR1v7Z512iwH6eom1JBQQ164zQ7cSD3uHey4c7rcpvuDTX4MkfB7WNqboMp0F+6AJ8s3mSpTtrnH3f/e659T/b8aAE+93AFxC1Y2AbBi0CWMQjklWrX3K9PKDD4TP5MfPZvdTcFMD6LQCinN9m5cVfxbq3qzRGlcIDYq4DgHJmFrpxI84tV5ayuvk0Tp1fvR1N9nxCsBFEF0N7QKkbSksCYIUKf6YXxCsFQgEosO1ZO8goYcjbn9k/f+gLatxDG8aTK938OfVD3hmO2EUVGFeZI1YsLWZEINDvxKkD0baVCzw73w18itoJeQHnFcYbK4qEwSUfUk0OKCggfhONcRJMzSw0TnnXu8JLvQo3nh6FlHU4hF7DKPeOJTnR/23R4zrv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
