travis:
  secure:
    BINSTAR_TOKEN: GVyuLeyQ0KZEI8gJfgBrW6r6WlboMM3f5KySih8kaCCbjOFsTlVgCYymiw7v52QeH316gyJA8+8OTJlzM7G9PlDOv8DWI+rHSnWfLKXSM8lm4GdYXyQ9Nhke0UDUDCUJUHC3aoPd2FZamdYxnfp1V/Qv3uMJmpsWRX4HYtR/WnEOQCGgCj9I4hgTUPCzU01X+YrarY4iFx2DJt5HW8TXQ4bOHy54Rpf4llZ+MkcSpHkOJInyU5pK3o8lFu2O/hwVS4C6Y6jA4fgdLGppTwHhB9ohQq3jKNwL1zW2NpyXJ3SpUnGhZ5PVk/gfirymOrj1sIQi3vtXV67GR54ZFrPQfK6UmFNXoCPxfxgP62RFRQa12xQMhsMTLeSfmIMzn8IBP53cnDtIE/RpnvLEepkYPTtj9WRxxCfp9+BwhTv6QkZsDuz8XRRgq0D1eVpZEK2HLTHDN6gCPAaJvaV+GSCjiInQrf8FDvLCTZPfej64FhjnPsbZsi43VM1HTQ+SNw31XhwN5VN3X38wsQQjEnmPNCXjb47tU+F5a+K+8UYqtN7rkusVsa7npPPPMvKkKHeBe1kwdQQ5j8vJkzoZ1x/kIUwxYVDH2zF1y2ZcCktTnm5oHcNPlARND/GI3vqVV4p3FXxwAcSr2RC+VTouAjLc9GIAKeey7tG86i876FPnBFU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
